### ISSUE TITLE
Total costs run against minus infinite

### ISSUE THREAD

**Issue by tscheypidi** [magpiemodel/magpie#137]
Under certain conditions `vm_bioenergy_utility`, which is subsidizing first generation bioenergy production, can lead to higher benefits than costs independent of the quantity of produced bioenergy, leading to a infinitely negative goal function.

Observed was this behavior when the model is run with trade realization "exo" and default data inputs.

The problematic lines of code are found here: 

https://github.com/magpiemodel/magpie/blob/3803f1aea82efc215218404509d7150bed2ecf3c/modules/60_bioenergy/1stgen_priced_dec18/equations.gms#L74:L75

My understanding is that these subsidies were introduced to prevent overproduction of other good in order to use their secondary products for bioenergy production. My feeling is that we need to get rid of the subsidy and need to treat the potential overproduction of other goods differently.

**Comment by flohump** [comment]
As far as I remember Benni added these subsidies.

**Comment by bodirsky** [comment]
Subsidies were included at low levels to provide more realistic prices.
If costs turn towards -Inf, this means that production costs must have turned inrealistically low. 

The subsidies are at very low levels, and represent very conservative opportunity costs of using these materials, e.g. vegetable oils as substitute for fossil fuels.

Given that the TC cost curve should lead to decreasing returns of scale, this seems to be a flaw rather on the supply side.

**Comment by tscheypidi** [comment]
that means we keep it and close the issue?

**Comment by bodirsky** [comment]
good question. I think we should still investigate why the production costs are so low? and why they fall for high pressure scenarios?
I guess, it is something like: country not self-sufficient --> a lot of TC needed to produce enough in first timestep --> then demand falls, yields stay very high, per-ha costs are very low?

**Comment by tscheypidi** [comment]
this is possible...problem occured with exo trade realization. Here, it is always possible to have suboptimal trade patterns causing such unusual trajectories. In that case this would be just an input data problem, not a modeling problem. I close the issue.
