### ISSUE TITLE
Slurm script output path conflicts with GAM -lf flag

### ISSUE THREAD

**Issue by ciaron** [magpiemodel/magpie#251]
The Slurm submit scripts set `--output` (stdout) flag to `full.log`, however the `submit.R` script also sets the `-lf` parameter to `full.log`

e.g. here
https://github.com/magpiemodel/magpie/blob/master/scripts/run_submit/submit_standby.sh
and here
https://github.com/magpiemodel/magpie/blob/master/scripts/run_submit/submit.R#L25

It looks like this causes either a) complete job failure (two attempts to open the same file for writing) or b) mixed Slurm and GAMS output.

Suggest setting `#SBATCH --output` to a unique value for the run, e.g. `full-%x-%j.log` (include jobname and job ID in the filename)

-c

**Comment by abhimishr** [comment]
Sorry for tagging your here @tscheypidi (I thought RSE side would have much clearer idea of how to move forward with this).
This is related to the failing runs we were also discussing in our internal mm channel.

**Comment by tscheypidi** [comment]
@ciaron thanks for pointing that out.

https://github.com/magpiemodel/magpie/pull/252 uses now slurm.log instead of full.log for slurm output
