### ISSUE TITLE
Timestamp missing in run names of automated model tests

### ISSUE THREAD

**Issue by giannou** [magpiemodel/magpie#357]
https://github.com/magpiemodel/magpie/blob/1f9bd81785e9eecf1cc8bbe8b12383c38c653b74/scripts/start/test_runs.R#L30

@flohump @tscheypidi is it important to have no time stamp in the folder name of the weekly test runs? The current implementation of the testing suite will not be able to distinguish them from each other.

**Comment by flohump** [comment]
For mindful use of storage capacites, the output folder of weekly test runs is overwritten each week. But the results are stored in shinyresults. shinyresults will add a date-time stamp automatically to distinguish weekly tests.

**Comment by giannou** [comment]
That makes sense @flohump , thanks. Will adjust the testing suite to the new scheme
