### ISSUE TITLE
Inconsistency of merge #614 with scenario config

### ISSUE THREAD

**Issue by DavidhoPIK** [magpiemodel/magpie#616]
The merge #614 deleted/ renamed the switch 
```cfg$gms$c31_past_suit_scen``` from default.cfg. 
However, in the scenario_config.cfg this switch still exists. 
This leads to an error when using ```gms::setScenario```.

**Comment by tscheypidi** [comment]
@flohump is currently working on incorporating a fix as part of pr #611

**Comment by DavidhoPIK** [comment]
Ok nice. Then I just close this issue.
