### ISSUE TITLE
8 `Emissions|CO2|Land` variables differ in 2000…2020 (caused by rcp setting?)

### ISSUE THREAD

**Issue by orichters** [magpiemodel/magpie#642]
Dear colleagues,

while running NGFS scenarios, I noticed the following:

Eight `Emissions|CO2|*` variables differ between scenarios already in 2005, 2010, 2015 and 2020, and I guess they shouldn't.

I also found that pattern in the MAgPIE automated tests:

<details>
<summary>Click here to see code to generate it</summary>

```
library(quitte); library(tidyverse); options(width = 160);
files <- file.path("/p/projects/landuse/tests/magpie/output", c("weeklyTests_SSP2EU-NDC", "weeklyTests_SSP2EU-PkBudg650"), "report.mif")
d <- quitte::as.quitte(files)
fails <- piamInterfaces::fixOnRef(files[[2]], files[[1]], startyear = 2025, ret = "fails")
for (f in levels(fails$variable)) {
  message("\n", f)
  d %>%
    filter(.data$region == "World", .data$variable == f, .data$period < 2022, .data$period > 2000) %>%
    df_variation() %>%
    droplevels() %>%
    pivot_wider(names_from = period) %>%
    print()
}
```
</details>

```
### Incorrect fixing for 8 variables (grouped below) for model=MAgPIE and scenario=weeklyTests_SSP2EU-PkBudg650
  group                          variables period              reldiff
1 Emissions|CO2|Land                     4 2005,2010,2015,2020 17.3 %
2 Emissions|CO2|Land Carbon Sink         2 2005,2010,2015,2020 9.09 %
3 Emissions|CO2|Land RAW                 2 2005,2010,2015,2020 36.1 %
```
```
Emissions|CO2|Land
  scenario                     `2005` `2010` `2015` `2020`
1 weeklyTests_SSP2EU-NDC        2025.  1644.  1993.  1622.
2 weeklyTests_SSP2EU-PkBudg650  2015.  1654.  1993.  1672.

Emissions|CO2|Land Carbon Sink|Cumulative|Grassi
  scenario                     `2005` `2010` `2015` `2020`
1 weeklyTests_SSP2EU-NDC        -18.6  -43.1  -68.4  -96.2
2 weeklyTests_SSP2EU-PkBudg650  -18.7  -43.1  -68.4  -96

Emissions|CO2|Land Carbon Sink|Grassi|Managed Land|Managed Forest
  scenario                     `2005` `2010` `2015` `2020`
1 weeklyTests_SSP2EU-NDC        -3720  -4900  -5060  -5570
2 weeklyTests_SSP2EU-PkBudg650  -3730  -4890  -5060  -5520

Emissions|CO2|Land RAW
  scenario                     `2005` `2010` `2015` `2020`
1 weeklyTests_SSP2EU-NDC        1596.  2135.  2797.  1313.
2 weeklyTests_SSP2EU-PkBudg650  1586.  2145.  2797.  1363.

Emissions|CO2|Land RAW|+|Indirect RAW
  scenario                     `2005` `2010` `2015` `2020`
1 weeklyTests_SSP2EU-NDC        -3720  -4900  -5060  -5570
2 weeklyTests_SSP2EU-PkBudg650  -3730  -4890  -5060  -5520

Emissions|CO2|Land|+|Indirect
  scenario                     `2005` `2010` `2015` `2020`
1 weeklyTests_SSP2EU-NDC        -3720  -4900  -5060  -5570
2 weeklyTests_SSP2EU-PkBudg650  -3730  -4890  -5060  -5520

Emissions|CO2|Land|Cumulative
  scenario                     `2005` `2010` `2015` `2020`
1 weeklyTests_SSP2EU-NDC         35.9   44.1   54.1   62.2
2 weeklyTests_SSP2EU-PkBudg650   35.8   44.1   54.1   62.4

Emissions|CO2|Land|Cumulative|+|Indirect
  scenario                     `2005` `2010` `2015` `2020`
1 weeklyTests_SSP2EU-NDC        -18.6  -43.1  -68.4  -96.2
2 weeklyTests_SSP2EU-PkBudg650  -18.7  -43.1  -68.4  -96
```

A similar result can be obtained for our recent NGFS runs using the `magpie release 4.7.0`. They can be found in  `/p/tmp/oliverr/NGFS_v5/remind-2024-02-27/magpie`. (Please don't run any experiment etc. in this folder.)

<details>
<summary>Click here to see code to generate it</summary>

```
library(quitte); library(tidyverse); options(width = 160);
d <- as.quitte(Sys.glob("/p/tmp/oliverr/NGFS_v5/remind-2024-02-27/magpie/output/C_*-mag-5/report.mif"))
fails <- piamInterfaces::fixOnRef(d, "C_h_cpol-mag-5", startyear = 2025, ret = "fails")

for (f in levels(fails$variable)) {
  message("\n", f)
  d %>%
    filter(.data$region == "World", .data$variable == f, .data$period < 2022) %>%
    df_variation() %>%
    droplevels() %>%
    pivot_wider(names_from = period) %>%
    print()
}
```
</details>

```
Emissions|CO2|Land
  scenario          `2005` `2010` `2015` `2020`
1 C_d_delfrag-mag-5   738.  -52.4  -91.7  -605.
2 C_d_strain-mag-5    858.   47.6   48.3  -475.
3 C_h_cpol-mag-5      858.   47.6   48.3  -475.
4 C_h_ndc-mag-5       858.   47.6   48.3  -475.
5 C_o_1p5c-mag-5      848.   57.6   48.3  -425.
6 C_o_2c-mag-5        738.  -52.4  -91.7  -605.
7 C_o_lowdem-mag-5    848.   57.6   48.3  -425.
8 C_SSP2-Base-mag-5   858.   47.6   48.3  -475.

Emissions|CO2|Land Carbon Sink|Cumulative|Grassi
  scenario          `2005` `2010` `2015` `2020`
1 C_d_delfrag-mag-5  -19.2  -44.2  -70.2  -98.7
2 C_d_strain-mag-5   -18.6  -43.1  -68.4  -96.2
3 C_h_cpol-mag-5     -18.6  -43.1  -68.4  -96.2
4 C_h_ndc-mag-5      -18.6  -43.1  -68.4  -96.2
5 C_o_1p5c-mag-5     -18.7  -43.1  -68.4  -96
6 C_o_2c-mag-5       -19.2  -44.2  -70.2  -98.7
7 C_o_lowdem-mag-5   -18.7  -43.1  -68.4  -96
8 C_SSP2-Base-mag-5  -18.6  -43.1  -68.4  -96.2

Emissions|CO2|Land Carbon Sink|Grassi|Managed Land|Managed Forest
  scenario          `2005` `2010` `2015` `2020`
1 C_d_delfrag-mag-5  -3840  -5000  -5200  -5700
2 C_d_strain-mag-5   -3720  -4900  -5060  -5570
3 C_h_cpol-mag-5     -3720  -4900  -5060  -5570
4 C_h_ndc-mag-5      -3720  -4900  -5060  -5570
5 C_o_1p5c-mag-5     -3730  -4890  -5060  -5520
6 C_o_2c-mag-5       -3840  -5000  -5200  -5700
7 C_o_lowdem-mag-5   -3730  -4890  -5060  -5520
8 C_SSP2-Base-mag-5  -3720  -4900  -5060  -5570

Emissions|CO2|Land RAW
  scenario          `2005` `2010` `2015` `2020`
1 C_d_delfrag-mag-5   394.   766. -210.   -645.
2 C_d_strain-mag-5    514.   866.  -69.7  -515.
3 C_h_cpol-mag-5      514.   866.  -69.7  -515.
4 C_h_ndc-mag-5       514.   866.  -69.7  -515.
5 C_o_1p5c-mag-5      504.   876.  -69.7  -465.
6 C_o_2c-mag-5        394.   766. -210.   -645.
7 C_o_lowdem-mag-5    504.   876.  -69.7  -465.
8 C_SSP2-Base-mag-5   514.   866.  -69.7  -515.

Emissions|CO2|Land RAW|+|Indirect RAW
  scenario          `2005` `2010` `2015` `2020`
1 C_d_delfrag-mag-5  -3840  -5000  -5200  -5700
2 C_d_strain-mag-5   -3720  -4900  -5060  -5570
3 C_h_cpol-mag-5     -3720  -4900  -5060  -5570
4 C_h_ndc-mag-5      -3720  -4900  -5060  -5570
5 C_o_1p5c-mag-5     -3730  -4890  -5060  -5520
6 C_o_2c-mag-5       -3840  -5000  -5200  -5700
7 C_o_lowdem-mag-5   -3730  -4890  -5060  -5520
8 C_SSP2-Base-mag-5  -3720  -4900  -5060  -5570

Emissions|CO2|Land|+|Indirect
  scenario          `2005` `2010` `2015` `2020`
1 C_d_delfrag-mag-5  -3840  -5000  -5200  -5700
2 C_d_strain-mag-5   -3720  -4900  -5060  -5570
3 C_h_cpol-mag-5     -3720  -4900  -5060  -5570
4 C_h_ndc-mag-5      -3720  -4900  -5060  -5570
5 C_o_1p5c-mag-5     -3730  -4890  -5060  -5520
6 C_o_2c-mag-5       -3840  -5000  -5200  -5700
7 C_o_lowdem-mag-5   -3730  -4890  -5060  -5520
8 C_SSP2-Base-mag-5  -3720  -4900  -5060  -5570

Emissions|CO2|Land|Cumulative
  scenario          `2005` `2010` `2015` `2020`
1 C_d_delfrag-mag-5   24.9   24.7   24.2   21.2
2 C_d_strain-mag-5    25.5   25.8   26.0   23.6
3 C_h_cpol-mag-5      25.5   25.8   26.0   23.6
4 C_h_ndc-mag-5       25.5   25.8   26.0   23.6
5 C_o_1p5c-mag-5      25.5   25.8   26.0   23.9
6 C_o_2c-mag-5        24.9   24.7   24.2   21.2
7 C_o_lowdem-mag-5    25.5   25.8   26.0   23.9
8 C_SSP2-Base-mag-5   25.5   25.8   26.0   23.6

Emissions|CO2|Land|Cumulative|+|Indirect
  scenario          `2005` `2010` `2015` `2020`
1 C_d_delfrag-mag-5  -19.2  -44.2  -70.2  -98.7
2 C_d_strain-mag-5   -18.6  -43.1  -68.4  -96.2
3 C_h_cpol-mag-5     -18.6  -43.1  -68.4  -96.2
4 C_h_ndc-mag-5      -18.6  -43.1  -68.4  -96.2
5 C_o_1p5c-mag-5     -18.7  -43.1  -68.4  -96
6 C_o_2c-mag-5       -19.2  -44.2  -70.2  -98.7
7 C_o_lowdem-mag-5   -18.7  -43.1  -68.4  -96
8 C_SSP2-Base-mag-5  -18.6  -43.1  -68.4  -96.2
```

The following settings are used:
```
d_delfrag: SSP2EU|NDC|nocc_hist|rcp2p6
d_strain : SSP2EU|NDC|nocc_hist|rcp4p5
h_cpol   : SSP2EU|NPI|nocc_hist|rcp4p5
h_ndc    : SSP2EU|NDC|nocc_hist|rcp4p5
o_1p5c   : SSP2EU|NDC|nocc_hist|rcp1p9
o_2c     : SSP2EU|NDC|nocc_hist|rcp2p6
o_lowdem : SSP2EU|NDC|nocc_hist|rcp1p9|NGFS_o_lowdem
SSP2-Base: SSP2EU|NPI|nocc_hist|rcp4p5
```

- As all runs using the same `rcp` setting are identical, I suspect that this setting is causing the problem.

**Comment by gabriel-abrahao** [comment]
This looks like it could be related to different carbon stocks from the cellullar inputs from LPJml. I suppose some numerical differece is to be expected since the whole input data is different per RCP, but I believe they should be the same in the files up to a certain year, and I remember something about a fixing in GAMS itself.

Tagging people that might know more here. @k4rst3ns do you happen to know after when the vegetation and soil C stocks diverge by default in the inputs? Any insights on whether there's a fixing to 1995 values somewhere? 

Another candidate could be a bug on the crop yields. @emolinab maybe you know something from the crop side? It's `nocc_hist`, so yields should be fixed before 2020 as far as I know, but do any recent changes come to mind? It's probably not this though, as I believe @orichters 's code would have picked up on differences in other variables.

**Comment by orichters** [comment]
What I noticed:
`modules/52_carbon/input/f52_land_carbon_sink_adjust_grassi.cs3` differs on RCP before 2020, and the output of `magpie4::landCarbonSink` differs between the scenarios:
```
   region period    cpol    twoc
 1 CHA      2005  -262.   -378.
 2 OAS      2005  -427.   -431.
 3 CHA      2010  -165.   -262.
 4 OAS      2010  -629.   -632.
 5 CHA      2015  -300.   -436.
 6 OAS      2015  -497.   -501.
 7 CHA      2020  -300.   -475.
 8 LAM      2020 -1350   -1340
 9 MEA      2020   -55.7   -54.9
10 OAS      2020  -738.   -724.
11 SSA      2020 -1114.  -1095.
```

**Comment by FelicitasBeier** [comment]
> This looks like it could be related to different carbon stocks from the cellullar inputs from LPJml. I suppose some numerical differece is to be expected since the whole input data is different per RCP, but I believe they should be the same in the files up to a certain year, and I remember something about a fixing in GAMS itself.
> 
> Tagging people that might know more here. @k4rst3ns do you happen to know after when the vegetation and soil C stocks diverge by default in the inputs? Any insights on whether there's a fixing to 1995 values somewhere?

For the inputs, they should be actually the same until 2010 and then afterwards they are fixed on a common future scenario until 2020. 

> 
> Another candidate could be a bug on the crop yields. @emolinab maybe you know something from the crop side? It's `nocc_hist`, so yields should be fixed before 2020 as far as I know, but do any recent changes come to mind? It's probably not this though, as I believe @orichters 's code would have picked up on differences in other variables.

The inputs should be fixed until 2020. 
* Years where SSPs and nocc/cc scenarios diverge
  sm_fix_SSP2               year until which all parameters are fixed to SSP2 values (year) / 2020 /
  sm_fix_cc                 year until which all parameters affected by cc are fixed to historical values (year) / 2020 /
;

**Comment by orichters** [comment]
I guess @flohump or @mikewin-climsci need to do some adjustments to AdjustGrassi2021 data.

**Comment by FelicitasBeier** [comment]
> What I noticed: `modules/52_carbon/input/f52_land_carbon_sink_adjust_grassi.cs3` differs on RCP before 2020, and the output of `magpie4::landCarbonSink` differs between the scenarios. For NGFS:
> 
> ```
>    region period    cpol    2c
>  1 CHA      2005  -262.   -378.
>  2 OAS      2005  -427.   -431.
>  3 CHA      2010  -165.   -262.
>  4 OAS      2010  -629.   -632.
>  5 CHA      2015  -300.   -436.
>  6 OAS      2015  -497.   -501.
>  7 CHA      2020  -300.   -475.
>  8 LAM      2020 -1350   -1340
>  9 MEA      2020   -55.7   -54.9
> 10 OAS      2020  -738.   -724.
> 11 SSA      2020 -1114.  -1095.
> ```
> 
> For the weekly test:
> 
> ```
>    region period    NDC  PkBudg650
>  1 LAM      2005 -1030   -1040
>  2 CAZ      2010  -187.   -182.
>  3 JPN      2010   -59.7   -54.2
>  4 LAM      2010 -1250   -1240
>  5 MEA      2010   -26.8   -27.2
>  6 SSA      2010  -653.   -663.
>  7 IND      2015  -133.   -125.
>  8 LAM      2015 -1090   -1100
>  9 OAS      2015  -497.   -495.
> 10 CHA      2020  -300.   -310.
> 11 IND      2020   -91.3   -83.0
> 12 LAM      2020 -1350   -1320
> 13 MEA      2020   -55.7   -56.5
> 14 NEU      2020   -62.8   -62.6
> 15 OAS      2020  -738.   -707.
> 16 REF      2020  -879.   -869.
> 17 SSA      2020 -1114.  -1134.
> ```

Oh, wow. Interesting. @flohump is that intended? They should be the same for all runs in the past, no?

**Comment by flohump** [comment]
Thanks for spotting! 
If the data differs in the input file before 2020 as pointed out by @orichters, we need to introduce a `sm_fix_cc` correction, which makes sure that before 2020 the same values are used irrespective of the choosen RCP.

**Comment by k4rst3ns** [comment]
Also another thought: Are the emissions are still smoothed via a low pass filter?
If so, it might mean that changes after 2020 could influence values before 2020.
But I remember we discussed that at some point and found a fix.

**Comment by orichters** [comment]
David had that suspicion as well, but it seems that [the lowpass is applied to historic and future data independently](https://github.com/pik-piam/magpie4/blob/44e1d8b1af10468b82db987f1519507fac4c0147/R/emisCO2.R#L484C1-L488C28) so you should not expect any leakage. And, this should definitely not extend to 2005 ;)

I'm quite confident that this issue can be fixed by basically reproducing line 55 also for the `else` case:

https://github.com/magpiemodel/magpie/blob/421b4f6a0daa13cbffc41de48cabc3b6a90590c8/modules/52_carbon/normal_dec17/input.gms#L53-L58

**Comment by flohump** [comment]
I have included a bugfix in PR637:
https://github.com/magpiemodel/magpie/pull/637/commits/577b558b5d340f65ecdfb037d12ac6204b34e078
The fix follow the same logic as used here:
https://github.com/magpiemodel/magpie/blob/master/modules/37_labor_prod/exo/input.gms#L25-L26

**Comment by orichters** [comment]
No idea why this wasn't closed automatically. But thanks for fixing it.
