### ISSUE TITLE
AGPL-3.0 licence is incompatible with GAMS code

### ISSUE THREAD

**Issue by robbiemorrison** [magpiemodel/magpie#80]
Great that PIK open sourced MAgPIE!  But you unfortunately chose an license incompatible with GAMS.

Version 3 of the GPL family of licenses is incompatible with GAMS code because Richard Stallman introduced a clause aimed at preventing its application to Java.  Back when version 3 was being drafted, Java was still proprietary and the new version of the GPL requires that the implementing language has either a recognized international standard (like C++) or an open source implementation.  As I understand it, GAMS currently fulfills neither of those requirements.

Quoting from the [SPDX site](https://spdx.org/licenses/GPL-3.0-only.html) in relation to GPL‑3.0:

> A "Standard Interface" means an interface that either is an **official standard defined by a recognized standards body**, or, in the case of interfaces specified for a particular programming language, **one that is widely used among developers working in that language**.

Note that there is no AGPL‑2.0 to apply instead.  I suggest you drop the "Affero" variant and use a GPL‑2.0‑only license.  Or simply drop back to a permissive license like MIT or ISC.

I undertook some analysis on selecting licenses for GAMS and I am of the general view that a copyleft license is not necessary, let alone the (incompatible) network variant:

- Morrison, Robbie (April 2018).  ["Energy system modeling: public transparency, scientific reproducibility, and open development"](https://www.sciencedirect.com/science/article/pii/S2211467X17300949/pdfft?md5=bec0fa165fae52cdeb539331df3e3c98&pid=1-s2.0-S2211467X17300949-main.pdf).  *Energy Strategy Reviews*.  **20**: 49–63.  ISSN [2211-467X](https://www.worldcat.org/issn/2211-467X).  doi:[10.1016/j.esr.2017.12.010](https://dx.doi.org/10.1016/j.esr.2017.12.010).  Open access.

I also contacted the Free Software Foundation on this matter and suggested they add this issue to their FAQ.  I had some traffic with their staff lawyer but FSF never added the question.

Happy to provide more details or put you in touch with people who served on the GPL version 3 drafting committee.  And, as I said, fantastic that PIK is heading open source.

**Comment by tscheypidi** [comment]
Thanks for your input. Could you please elaborate a bit more. I looked again into the GPL license text and found that passage about standard interface. However, it is unclear to me how this links to your claim that the license is incompatible with GAMS code. Especially, I could not find a statement claiming that the language has to be a recognized standard or open source. To my understanding the quoted sentence is talking about something else (at least it does not mention open source).

**Comment by robbiemorrison** [comment]
I can elaborate but first I need to talk to a corporate engineer that participated on the GPL‑3.0 drafting committee. If I don't get an answer there, I'll post a question to the FSFE Legal Network mailing list. I am pretty sure I am correct but I agree that the license text is not especially clear. Give me a few days.

By the way, talking about the non‑Affero GPL text is fine because the Affero conditions are separate and additional to the standard GPL.

**Comment by tscheypidi** [comment]
cool, thanks!

**Comment by robbiemorrison** [comment]
Here is the response from my engineering contact, now retired, who served on the GPLv3 drafting committee representing a well known United States corporation:

> There is such a provision in (A)GPLv3, albeit not called out clearly and directly.  It's implemented in kind of spaghetti legal code in section&nbsp;1, and it's defined by backtracking through the exceptions.  The Corresponding Source for a covered program includes the program's source code plus the source code for any Major Component (including compilers and runtime libraries) needed to compile and run the program.  However, a Major Component is excepted from Corresponding Source if it is a System Library, a general-purpose tool, or a generally available free program.  To be a System Library, you need [via] a packaging tool like RPM, or be shipped with the operating system, or implement as a Standard Interface for which an implementation is available to the public in source code.  Java, before Sun/Oracle open sourced the language, would not have qualified under this definition of a System Library.  Therefore, since you had no rights to release the Sun/Oracle runtimes or compiler in source, you could not release any Java program under terms of version&nbsp;3 because it would have been impossible to provide the Corresponding Source.
>
> From what you have told me of GAMS, it is not a packaging tool; it is not shipped with the operating system; the language itself does not have a recognized definition as a standard; the source code for a version of GAMS is not available.  By my non-lawyer analysis, you are stuck if you offer a GAMS program under GPLv3, because you, too, can't provide the Corresponding Source.
>
> This analysis changes instantly if someone, somewhere, anywhere, has released an open source implementation of GAMS (and it doesn't have to be the exact version you are using).
>
> If I were still running the open source compliance program at [US corporation redacted] and a developer came to me with a proposal to release a program written in a proprietary programming language (a situation that happens all the time in the open source hardware world, alas) under GPLv3 I would advise them not to do so.  The GPLv3 language is *incredibly* tortured but the intent, at least, is clear.  It's not really free software if you must buy non-free tools to compile and run it.
>
> If you really, really want to use AGPLv3 and no other copyleft license will do, maybe you can finesse the problem by adding an Additional Permission to the source exempting the user from the requirement to release GAMS as Corresponding Source.  That would at least make your intention clear.

Happy to post to the FSFE list I mentioned earlier if you need further clarification.

For the record, here is what I said about GAMS:

> If you are not familiar with GAMS, it is a proprietary algebraic modeling language widely used in economics and operations research and also used to build integrated assessment models. GAMS models are first "translated" into a basic linear programming data structure and then passed to a suitable solver. Normal software issues like libraries and linking more generally do not apply, nor is there ever any object code produced. Translation is essentially an exercise in generating data in a form that can be passed though an API to a supported solver.

**Comment by robbiemorrison** [comment]
A note on open source license identifiers.  GPLv3 and GPLv3+ are historical shorthand for the version&nbsp;3.0 license, the latter allowing any later version at the discretion of the user.  The [SPDX](http://www.wikipedia.org/wiki/SPDX) equivalent license identifiers are now GPL‑3.0‑only and GPL‑3.0‑or‑later, respectively.  Ditto for version&nbsp;2.0.

**Comment by robbiemorrison** [comment]
Just to clarify.  It is a convention for open licenses that if any condition is violated then the entire license is withdrawn.  The GPL‑3.0 family is a little different in that section&nbsp;8 offers a 30‑day "cure" period for violators to come into compliance.  But that provision applies to downstream users and not to this situation.

In the case of an incorrect application of the license — as is presumed here — the entire license is void.  This means that under United States and German copyright law, no rights are granted to build and/or run the program (Jaeger and Metzger 2016:129, Meeker 2017:148).  Therefore, MAgPIE, under its current legal status, is not open source software and should not be describes as such.  Users who clone from this repository are legally entitled to inspect the code but nothing more.  HTH R.

**References**

Jaeger, Till and Axel Metzger (21 March 2016).  *Open Source Software: Rechtliche Rahmenbedingungen der Freien Software* (4. Ausgabe) [*Open source software: legal framework for free software* (4th ed)] (in German).  Munich, Germany: CH Beck.  ISBN 978-3-406-67773-1.

Meeker, Heather (4 April 2017).  *Open (source) for business: a practical guide to open source software licensing* (2nd edition).  North Charleston, South Carolina, USA: CreateSpace Independent Publishing Platform.  ISBN 978-154473764-5.

**Comment by tscheypidi** [comment]
Thanks for the additional information. We are in contact with Till Jäger and hope to get this issue clarified as soon as possible.

**Comment by robbiemorrison** [comment]
Noted and thanks.  I occasionally run into Till.  Will be interested in the outcome, not being a lawyer myself.

**Comment by tscheypidi** [comment]
We got that thing now sorted out. From Till Jägers perspective it is debatable whether there was a licensing issue in the first place or not, depending on whether GAMS and the corresponding solver libraries should be accounted as system libraries or not. As it was unclear he suggested to add an additional permission to the license text, as allowed in section 7 of the AGPL3 license, which releases the user from the burden to also release sourcecode from surrounding GAMS and solver libraries. 

In addition, it also covers now another case dealing with incompatible open source licenses in used R packages. Apparently, the GDXRRW R package currently uses such a non-GPL-compatible license.

The additional permission reads as follows:

https://github.com/magpiemodel/magpie/blob/950bc7a08fd0e6c8f790c1399c7837133233e2fc/LICENSE#L13-L42

Through this additional permission the license issue is solved independent of the applied categorization of the GAMS and solver environment.

Thanks again for raising awareness of the licensing issue.

**Comment by robbiemorrison** [comment]
Thanks.  Viewing the GAMS development environment as a GPLv3 system library exception is an unexpected result, as for me.  Although I&nbsp;am not in a position to comment on the detailed legal issues of course.  But the interpretation of open licenses is treated as a community issue by open source advocates.  Unlike proprietary licenses in this regard, whereby disputed interpretation rests solely with the parties involved.  So I'll bring this bug report to the attention of the Free Software Foundation Europe Legal Network mailing list in a few moments.  I am sure some on the list will be interested in this result, either because it adds clarity or because they disagree.  Or probably both.  Till is also an active member on the list, but I'll copy him in personally in any case.

Just to make clear that my interest is not that MAgPIE relicenses to some other open license.  Licensing is entirely your call.  But to clarify the suitability of the GPLv3 to GAMS programs more generally plus any need for additional legal clarification.  This is an issue of broad interest.  The Free Software Foundation (the US variant) is currently updating its licensing FAQ and any final view of the community should ideally be recorded there for a wider audience.  In any case, I&nbsp;will report back on those discussions in due course.  With best wishes.

**Comment by robbiemorrison** [comment]
Nothing of significance to report from my earlier posting to the Free Software Foundation Europe (FSFE) Legal Network (LN) mailing list.
